services:
  db:
    build: ./postgresql
    restart: unless-stopped
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      SCHEMA: public
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    command: 
      - "postgres"
      - "-c" 
      - "shared_preload_libraries=pg_cron"
      - "-c"
      - "cron.database_name=postgres"
      - "-c"
      - "cron.log_run=on"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3